version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payloadpassword
      POSTGRES_DB: payload
    volumes:
      - data:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  data:
  node_modules:
